GET http://localhost:3000/api/users
content-type: application/json
db-limit: 100

###

GET http://localhost:3000/api/users/66
content-type: application/json

###

DELETE http://localhost:3000/api/users/68
content-type: application/json

###
POST http://localhost:3000/api/users
content-type: application/json

{
  "email": "winnie@pooh.org",
  "givenname": "Winnie",
  "familyname": "Pooh",
  "updated": "2021-11-14T14:48:17Z"
}

###
PATCH http://localhost:3000/api/users/66
content-type: application/json

{
  "givenname": "Mickey",
  "familyname": "Mouse",
  "updated": "2021-11-14T14:48:17Z"
}

###

